# Generated by Django 2.1.3 on 2018-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T004', '0002_transacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacoes',
            new_name='Transacao',
        ),
    ]
