# Generated by Django 2.2.2 on 2019-06-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T004', '0003_auto_20181124_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
    ]
